config: version 0.0.3
input:
  url: "https://www.foto-webcam.eu/webcam/wendelstein/current/1920.jpg"
  info: "https://www.foto-webcam.eu/webcam/wendelstein/infos/"
  provider: "https://www.foto-webcam.eu/webcam/infos/"
  link: "https://www.foto-webcam.eu/webcam/wendelstein/"
  crop_factor: 1.1
  offset_x: -0.11
  offset_y: 0.05

scheduling:
  update_interval_minutes: 10

image_processing:
  blur_strength: 1.0
  contrast: 1.5
  saturation: 0.6
  brightness: 0.0
  hue: 0.0
  gamma: 1.0
  black_point: 0.0
  white_point: 1.0
  shadow_strength: 1.0
  sharpen_strength: 0.0
  max_noise_opacity: 0.05
  noise_scale: 2

output:
  save_path: "foto_webcam_eu"
